# Define how Node packages should be installed.
# Create a node_modules folder just like in Yarn Classic or npm.
nodeLinker: node-modules

# Explicitly add compression level to 0 to make --immutable option work properly
# across different systems.
compressionLevel: 0

# Do not send anonymous telemetry data.
enableTelemetry: false